name: Build then Deploy to Azure Spring Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: app
        id: download
      - name: Get JAR file name
        run: echo "::set-output name=jar-file::$(ls ${{ steps.download.outputs.download-path }}/*.jar)"
        id: get-jar
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get Subscription ID
        run: |
          subscription_id=$(az account show --query 'id' -o tsv)
          echo "::set-output name=subscription_id::$subscription_id"
        id: subscription
      - name: Deploy to Azure Spring Apps
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ steps.subscription.outputs.subscription_id }}
          service-name: ${{ env.SERVICE }}
          app-name: ${{ env.APP_NAME }}
          package: ${{ steps.get-jar.outputs.jar-file }}
          builder: ${{ env.BUILDER }}
          action: deploy
          use-staging-deployment: false
        env:
          RESOURCE_GROUP: springoneent
          SERVICE: springoneent
          APP_NAME: springone
          BUILDER: springone